version: '3.8'
services:
  openvpn:
    build:
      context: ./

    cap_add:
     - NET_ADMIN

    container_name: openvpn
    ports:
     - "3749:1194/tcp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
